### PR TITLE
Updated site mobile checker links

### PR DESCRIPTION
**Pull request by michaelborn**
I removed the [W3C link](https://validator.w3.org/mobile/) because it has been taken down. I instead added links to Google, Bing, and minify.mobi mobile site checkers.

### CODE REVIEW

**Comment by alaskanloops** [comment]
The end of an era.

**Review by filipechagas — CHANGES_REQUESTED** [review]
Thanks for contributing!

Can you please update the PR with latest master changes?

**Comment by michaelborn** [comment]
Lol... five years later, can I merge in changes?

I certainly can... though it may take a few years. :laughing:  I'll keep ya posted, hopefully can do this tomorrow.

**Comment by michaelborn** [comment]
Ok, so I finally checked this over. This link was fixed or removed in 2017: https://github.com/toptal/webdevchecklist.com/commit/6909b02048abaf64276066f2776605ba7f662470

**Pull request closed without merging**
